export const popupSettingActionType = {
  CHANGE_HIGHLIGHT_COLOR: 'CHANGE_HIGHLIGHT_COLOR',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  CHANGE_FONT_SIZE: 'CHANGE_FONT_SIZE',
  CHANGE_SHOW_DETAIL: 'CHANGE_SHOW_DETAIL',
  ADD_SUSPENDED_PAGES: 'ADD_SUSPENDED_PAGES',
  DEL_SUSPENDED_PAGES: 'DEL_SUSPENDED_PAGES',
  OVERRIDE_ALL: 'OVERRIDE_ALL',
};
