// For redux

export const AUTH_STATUS = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
};

export const FORM_STATUS = {
  FETCH_FORMS_SUCCESS: 'FETCH_FORMS_SUCCESS',
  FETCH_FORMS_FAIL: 'FETCH_FORMS_FAIL',
  FETCH_FORM_SUCCESS: 'FETCH_FORM_SUCCESS',
  FETCH_FORM_FAIL: 'FETCH_FORM_FAIL',
  FETCH_TODO_FORMS_SUCCESS: 'FETCH_USER_FORMS_SUCCESS',
  FETCH_TODO_FORMS_FAIL: 'FETCH_USER_FORMS_FAIL',
};

export const MESSAGE_STATUS = {
  SET_MESSAGE: 'SET_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
};

export const LOAN_STATUS = {
  FETCH_LOAN_SUCCESS: 'FETCH_LOAN_SUCCESS',
  FETCH_LOAN_FAILED: 'FETCH_LOAN_FAILED',
};
