export const HIGHLIGHTER_CHECK_INTERVAL = 5000;
export const BACKGROUND_INIT_SETUP_DELAY = 5000;

export const HIGHLIGHTER_CLASS = 'HIGHLIGHTER_CLASS';
export const HIGHLIGHTER_DETAIL_CLASS = 'HIGHLIGHTER_DETAIL_CLASS';
export const HIGHLIGHTER_DETAIL_ITEM_CLASS = 'HIGHLIGHTER_DETAIL_ITEM_CLASS';
export const HIGHLIGHTER_ORG_WORD_CLASS = 'HIGHLIGHTER_ORG_WORD_CLASS';
export const HIGHLIGHTER_TARGET_WORD_CLASS = 'HIGHLIGHTER_TARGET_WORD_CLASS';
export const HIGHLIGHTER_POS_CLASS = 'HIGHLIGHTER_POS_CLASS';
export const HIGHLIGHTER_DEF_CLASS = 'HIGHLIGHTER_DEF_CLASS';
export const HIGHLIGHTER_ICON_CLASS = 'HIGHLIGHTER_ICON_CLASS';
export const HIGHLIGHTER_LINK_CLASS = 'HIGHLIGHTER_LINK_CLASS';
export const HIGHLIGHTER_DETAIL_HIDDEN_CLASS = 'HIGHLIGHTER_DETAIL_HIDDEN_CLASS';

export const HIGHLIGHTER_BG_COLOR_CLASS = {
  PINK: 'HIGHLIGHTER_BG_COLOR_CLASS_PINK',
  ORANGE: 'HIGHLIGHTER_BG_COLOR_CLASS_ORANGE',
  YELLOW: 'HIGHLIGHTER_BG_COLOR_CLASS_YELLOW',
  GREEN: 'HIGHLIGHTER_BG_COLOR_CLASS_GREEN',
  BLUE: 'HIGHLIGHTER_BG_COLOR_CLASS_BLUE',
  PURPLE: 'HIGHLIGHTER_BG_COLOR_CLASS_PURPLE',
};

export const HIGHLIGHTER_FONT_SIZE_CLASS = {
  SMALL: 'HIGHLIGHTER_FONT_SIZE_CLASS_SMALL',
  MEDIUM: 'HIGHLIGHTER_FONT_SIZE_CLASS_MEDIUM',
  LARGE: 'HIGHLIGHTER_FONT_SIZE_CLASS_LARGE',
};

export const ONLINE_DIC_URL = {
  en: 'https://dictionary.cambridge.org/dictionary/english/',
  es: 'https://dictionary.cambridge.org/dictionary/english-spanish/',
  zh_TW: 'https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/',
  zh_CN: 'https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B0%A1%E9%AB%94/',
};

export const PARTS_OF_SPEECH_SHORTHAND = {
  noun: '(n.)',
  verb: '(v.)',
  adverb: '(adv.)',
  adjective: '(adj.)',
  preposition: '(prep.)',
  conjunction: '(conj.)',
};

export const HIGHLIGHTER_FONT_SIZE = {
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
};

export const HIGHLIGHTER_BG_COLORS = {
  PINK: 'PINK',
  ORANGE: 'ORANGE',
  YELLOW: 'YELLOW',
  GREEN: 'GREEN',
  BLUE: 'BLUE',
  PURPLE: 'PURPLE',
};

export const LANGS = {
  en: 'en',
  es: 'es',
  zh_TW: 'zh_TW',
  zh_CN: 'zh_CN',
};
