export const EXT_STORAGE_AUTH_TOKEN = 'EXT_STORAGE_AUTH_TOKEN';

export const EXT_STORAGE_USER = 'EXT_STORAGE_USER';

export const EXT_STORAGE_CONFIG = 'EXT_STORAGE_CONFIG';

export const EXT_STORAGE_DAILY_WORD = 'EXT_STORAGE_DAILY_WORD';

export const EXT_STORAGE_WORD_LIST = 'EXT_STORAGE_WORD_LIST';

export const EXT_STORAGE_LAST_SYNC_UP_TIME = 'EXT_STORAGE_LAST_SYNC_UP_TIME';
